# Generated by Django 5.0.7 on 2024-07-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('ref', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proc', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LotProcessus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_debut', models.DateTimeField()),
                ('temps_fin', models.DateTimeField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.lot')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.processus')),
            ],
            options={
                'unique_together': {('lot', 'processus')},
            },
        ),
    ]
