# Generated by Django 5.0.7 on 2024-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotprocessus',
            name='temps_fin',
        ),
        migrations.AlterField(
            model_name='processus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
