# Generated by Django 5.0.7 on 2024-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_remove_lotprocessus_temps_fin_alter_processus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotprocessus',
            name='temps_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
