# Generated by Django 5.0.7 on 2024-07-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_lotprocessus_temps_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='processus',
            name='durée',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
