# Generated by Django 5.0.7 on 2024-07-25 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0004_processus_durée'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processus',
            name='durée',
        ),
        migrations.AddField(
            model_name='processus',
            name='duree',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
