# Generated by Django 5.0.7 on 2024-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0005_remove_processus_durée_processus_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processus',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
