# Generated by Django 5.0.7 on 2024-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0006_alter_processus_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processus',
            name='duree',
            field=models.IntegerField(default=0),
        ),
    ]
