# Generated by Django 5.0.7 on 2024-07-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0007_alter_processus_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_reclamation', models.DateTimeField()),
                ('le_message', models.TextField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.lot')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.processus')),
            ],
            options={
                'unique_together': {('lot', 'processus')},
            },
        ),
    ]
