# Generated by Django 5.0.7 on 2024-07-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0008_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('lot', 'processus', 'temps_reclamation')},
        ),
    ]
