# Generated by Django 5.0.7 on 2024-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0010_message_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotprocessus',
            name='temps_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
